# coding: utf-8

# flake8: noqa

"""
    Social Media Microblog API

    A Twitter-like microblog API built with FastAPI and SQLite. Supports creating posts (max 280 chars) and liking posts (once per user).

    The version of the OpenAPI document: 1.0.0
    Contact: dev@microblog.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "HealthApi",
    "PostsApi",
    "TagsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "HTTPValidationError",
    "LikeRequest",
    "LikeResponse",
    "LocationInner",
    "PostCreate",
    "PostResponse",
    "TrendingTag",
    "ValidationError",
]

# import apis into sdk package
from openapi_client.api.health_api import HealthApi as HealthApi
from openapi_client.api.posts_api import PostsApi as PostsApi
from openapi_client.api.tags_api import TagsApi as TagsApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.http_validation_error import HTTPValidationError as HTTPValidationError
from openapi_client.models.like_request import LikeRequest as LikeRequest
from openapi_client.models.like_response import LikeResponse as LikeResponse
from openapi_client.models.location_inner import LocationInner as LocationInner
from openapi_client.models.post_create import PostCreate as PostCreate
from openapi_client.models.post_response import PostResponse as PostResponse
from openapi_client.models.trending_tag import TrendingTag as TrendingTag
from openapi_client.models.validation_error import ValidationError as ValidationError

