# coding: utf-8

# flake8: noqa
"""
    Social Media Microblog API

    A Twitter-like microblog API built with FastAPI and SQLite. Supports creating posts (max 280 chars) and liking posts (once per user).

    The version of the OpenAPI document: 1.0.0
    Contact: dev@microblog.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.http_validation_error import HTTPValidationError
from openapi_client.models.like_request import LikeRequest
from openapi_client.models.like_response import LikeResponse
from openapi_client.models.location_inner import LocationInner
from openapi_client.models.post_create import PostCreate
from openapi_client.models.post_response import PostResponse
from openapi_client.models.trending_tag import TrendingTag
from openapi_client.models.validation_error import ValidationError

