# coding: utf-8

# flake8: noqa

"""
    Social Media Microblog API

    A Twitter-like microblog API built with FastAPI and SQLite. Supports creating posts (max 280 chars) and liking posts (once per user). Includes real-time SSE feed, ETag conditional caching, and per-IP rate limiting.

    The version of the OpenAPI document: 1.0.0
    Contact: dev@microblog.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AuthApi",
    "HealthApi",
    "PostsApi",
    "RealtimeApi",
    "TagsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "CommentCreate",
    "CommentResponse",
    "HTTPValidationError",
    "LikeRequest",
    "LikeResponse",
    "LocationInner",
    "PostCreate",
    "PostResponse",
    "TrendingTag",
    "UserCreate",
    "UserLogin",
    "UserResponse",
    "ValidationError",
]

# import apis into sdk package
from microblog_sdk.api.auth_api import AuthApi as AuthApi
from microblog_sdk.api.health_api import HealthApi as HealthApi
from microblog_sdk.api.posts_api import PostsApi as PostsApi
from microblog_sdk.api.realtime_api import RealtimeApi as RealtimeApi
from microblog_sdk.api.tags_api import TagsApi as TagsApi

# import ApiClient
from microblog_sdk.api_response import ApiResponse as ApiResponse
from microblog_sdk.api_client import ApiClient as ApiClient
from microblog_sdk.configuration import Configuration as Configuration
from microblog_sdk.exceptions import OpenApiException as OpenApiException
from microblog_sdk.exceptions import ApiTypeError as ApiTypeError
from microblog_sdk.exceptions import ApiValueError as ApiValueError
from microblog_sdk.exceptions import ApiKeyError as ApiKeyError
from microblog_sdk.exceptions import ApiAttributeError as ApiAttributeError
from microblog_sdk.exceptions import ApiException as ApiException

# import models into sdk package
from microblog_sdk.models.comment_create import CommentCreate as CommentCreate
from microblog_sdk.models.comment_response import CommentResponse as CommentResponse
from microblog_sdk.models.http_validation_error import HTTPValidationError as HTTPValidationError
from microblog_sdk.models.like_request import LikeRequest as LikeRequest
from microblog_sdk.models.like_response import LikeResponse as LikeResponse
from microblog_sdk.models.location_inner import LocationInner as LocationInner
from microblog_sdk.models.post_create import PostCreate as PostCreate
from microblog_sdk.models.post_response import PostResponse as PostResponse
from microblog_sdk.models.trending_tag import TrendingTag as TrendingTag
from microblog_sdk.models.user_create import UserCreate as UserCreate
from microblog_sdk.models.user_login import UserLogin as UserLogin
from microblog_sdk.models.user_response import UserResponse as UserResponse
from microblog_sdk.models.validation_error import ValidationError as ValidationError

