# coding: utf-8

"""
    Social Media Microblog API

    A Twitter-like microblog API built with FastAPI and SQLite. Supports creating posts (max 280 chars) and liking posts (once per user).

    The version of the OpenAPI document: 1.0.0
    Contact: dev@microblog.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.posts_api import PostsApi


class TestPostsApi(unittest.TestCase):
    """PostsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PostsApi()

    def tearDown(self) -> None:
        pass

    def test_create_post_posts_post(self) -> None:
        """Test case for create_post_posts_post

        Create a new post
        """
        pass

    def test_get_posts_posts_get(self) -> None:
        """Test case for get_posts_posts_get

        Get all posts
        """
        pass

    def test_like_post_posts_post_id_like_post(self) -> None:
        """Test case for like_post_posts_post_id_like_post

        Like a post
        """
        pass


if __name__ == '__main__':
    unittest.main()
