# coding: utf-8

"""
    Social Media Microblog API

    A Twitter-like microblog API built with FastAPI and SQLite. Supports creating posts (max 280 chars) and liking posts (once per user).

    The version of the OpenAPI document: 1.0.0
    Contact: dev@microblog.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.trending_tag import TrendingTag

class TestTrendingTag(unittest.TestCase):
    """TrendingTag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrendingTag:
        """Test TrendingTag
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TrendingTag`
        """
        model = TrendingTag()
        if include_optional:
            return TrendingTag(
                tag = '',
                count = 56
            )
        else:
            return TrendingTag(
                tag = '',
                count = 56,
        )
        """

    def testTrendingTag(self):
        """Test TrendingTag"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
