# coding: utf-8

"""
    Social Media Microblog API

    A Twitter-like microblog API built with FastAPI and SQLite. Supports creating posts (max 280 chars) and liking posts (once per user).

    The version of the OpenAPI document: 1.0.0
    Contact: dev@microblog.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.like_response import LikeResponse

class TestLikeResponse(unittest.TestCase):
    """LikeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LikeResponse:
        """Test LikeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LikeResponse`
        """
        model = LikeResponse()
        if include_optional:
            return LikeResponse(
                message = '',
                total_likes = 56
            )
        else:
            return LikeResponse(
                message = '',
                total_likes = 56,
        )
        """

    def testLikeResponse(self):
        """Test LikeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
